### ISSUE TITLE
server_name tag has initialized at build server

### ISSUE THREAD

**Issue by satiu** [getsentry/sentry-symfony#102]
Hello! I have faced an issue that all Sentry issues contain the same server_name tag.

I build an application once time on a CI server, then deploy already cache-warmed app to production stage.

I see all Sentry issues contain my CI server name instead of production server name, where an error had been occured.

I use sentry-symfony 1.0.1 and sentry 1.8.2 in my dependencies.

**Comment by Jean85** [comment]
I've track down the `server_name` tag to the client, and it uses a basic `gethostname()` function call to determine the name of the server, see http://php.net/manual/en/function.gethostname.php.

You should investigate on your build (it's Docker?) to see if it's porting over some info from the build inside the artifact itself, since the value is fetched at capture time, so it shouldn't matter if you build the application in this way.

I have a CD setup where I build Docker containers and ship those to prod, and in that case I get an hex string as `server_name`, and it's the host name inside the PHP container (i.e. `925919126b6c`), the same that I get with other reporting tools like NewRelic.

**Comment by satiu** [comment]
I ship only the app directory with sources, dependencies and warmed cache. And I just switch symlink to the folder on production servers. Is `server_name` has been persisted in a cache directory?

**Comment by Jean85** [comment]
No is not. As I said before, I have at least one app that I ship inside a Docker container with warmed up cache included, and I do not have this issue. Did you add any kind of call to the Sentry client?

**Comment by satiu** [comment]
No, I do `php bin/console cache:warmup --env=prod` only. I guess the problem is when `appProdProjectContainer.php` file has generated.
getSentry_ClientService function contains this lines
` $this->services['sentry.client'] = $instance = new \Sentry\SentryBundle\SentrySymfonyClient($this->getEnv('SENTRY_DSN'), array('release' => 'release_2a093c22a7', 'environment' => $this->getEnv('APP_ENV'), 'error_types' => 'E_ALL', 'timeout' => 3, 'logger' => 'php', 'server' => NULL, 'secret_key' => NULL, 'public_key' => NULL, 'project' => 1, 'auto_log_stacks' => false, 'name' => 'runner-66745b70-project-111-concurrent-0'
...`

so `name` item has string value of my CI server instead of Environment variable.

**Comment by Jean85** [comment]
Still, it's something strange. The warmup step should be done in the Docker build phase: my Dockerfile for example looks like this:

``Dockerfile
ENV SYMFONY_ENV prod
COPY composer.* ./
RUN composer install $COMPOSER_FLAGS --no-scripts --no-autoloader

ADD . ./

RUN mkdir var \
    && mv -f app/config/parameters.yml.$SYMFONY_ENV app/config/parameters.yml.dist \
    && composer install $COMPOSER_FLAGS \
    && bin/console cache:warmup --ansi --env=$SYMFONY_ENV
```
so the CI should be hidden in that step.. Are you doing it like that?
If possible, can you share your (eventually redacted) Dockerfile so I can help you diagnose this?

**Comment by hjanuschka** [comment]
we switched to ENV based "hostname" 👍 


```yaml
parameters:
    env(KRN_SENTRY_ENV): 'undefined'
    env(KRN_SENTRY_RELEASE): 'undefined'
    env(KRN_MY_HOSTNAME): 'undefined'
    env(KRN_SENTRY_DSN): 'https://b97e9a0427ca49e2872840c857a369ac:de66c967d0c74ff781ec2fed952ec610@sentry.krone.at/2'

sentry:
    dsn: "%env(KRN_SENTRY_DSN)%"
    options:
        environment: "%env(KRN_SENTRY_ENV)%"
        release: "%env(KRN_SENTRY_RELEASE)%"
        name: "%env(KRN_MY_HOSTNAME)%"
    skip_capture:
      - "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException"

```

setting the env - in the docker start command with `KRN_MY_HOSTNAME=$(hostname) docker-compose yadayada`
