### ISSUE TITLE
Support Raven_Breadcrumbs_MonologHandler

### ISSUE THREAD

**Issue by ruudk** [getsentry/sentry-symfony#165]
It would be great if the Symfony bundle would automatically (when enabled in config) register this handler to Monolog.

That way, we can use Sentry Breadcrumbs as the logger. It will send it to the log file as to Sentry.

**Comment by Jean85** [comment]
What do you mean by "push it to sentry.logger_service"? And how would you link all of this to your full Monolog configuration?

**Comment by ruudk** [comment]
I looked into it, and it seems that it's very simple to just configure this outside this bundle:
```yaml
services:
    sentry.monolog_breadcrumbs_handler:
        class: 'Raven_Breadcrumbs_MonologHandler'
        arguments:
            - '@sentry.client'

monolog:
    handlers:
        sentry:
            type: service
            id: sentry.monolog_breadcrumbs_handler
```

Might be nice to add to the documentation.
