### ISSUE TITLE
Preventing 404 pages from being reported as errors

### ISSUE THREAD

**Issue by karlbuckland** [getsentry/sentry-symfony#216]
I'm using Symfony 4 and error reporting is working, but 404 pages are getting reported too.

I can see that they used to be excluded by default, but presumably the code has been refactored since. I have tried adjusting my sentry.yaml:
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        excluded_exceptions:
            - 'Symfony\Component\Routing\Exception\ResourceNotFoundException'
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
```

Now, Sentry is still reporting the 404's but as '<unlabeled event>'. 

Presumably I'm missing something obvious?

**Comment by Jean85** [comment]
This is a known issue relative to the base SDK, which has already been reported in getsentry/sentry-php#820.

**Comment by Jean85** [comment]
getsentry/sentry-php#822 has been merged. Please test it, it should fix your issue:
```
composer require sentry/sentry:dev-master
```

**Comment by karlbuckland** [comment]
Yes - that has fixed the issue. Thank you!

**Comment by Jean85** [comment]
The fix has been released in the base SDK as 2.1.1: https://github.com/getsentry/sentry-php/releases/tag/2.1.1

A simple `composer update` (or the removal of the suggested workaround) is enough!

**Comment by kissifrot** [comment]
Does that mean the NotFoundHttpException exceptions are no longer caught by sentry or do we still have to list them as excluded?

**Comment by Jean85** [comment]
It means that you still need to list them as excluded, and now the option is behaving properly.

**Comment by rvanlaak** [comment]
Also see https://github.com/getsentry/sentry-symfony/issues/128#issuecomment-549871615

It seems that 404s and authentication exceptions are getting reported again since we rolled out the update to `sentry/sentry-symfony` v3.2.0 today.

We had a default config applied and solved it by adding `excluded_exceptions`:


```yaml
sentry:
    # ...
    options:
        # ...
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AuthenticationException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
```
