### ISSUE TITLE
Improve documentation about config

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#224]
I've made a huge update with sentry, updating from `0.8.*` to `3.0.*`.
Now I received error message for every `Symfony\Component\Security\Core\Exception\AccessDeniedException`.

I'd like to ignore this options. I found some post talking about an `excluded_exceptions` but I found no documentation about it...

The https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk section should be updated with all the available option and how to use them.

**Comment by Jean85** [comment]
We already addressed this in #207 and fixed it with #208. We have a dedicated upgrade document, and all the additional options come from the base SDK, that has its own documentation: https://docs.sentry.io/error-reporting/configuration/?platform=php

**Comment by VincentLanglet** [comment]
A new user won't look at the upgrade document to know the config option. You should not consider this as a documentation.

I think it will still be a good improvement to give a full example of config in the README, like this
```
sentry:
    dsn: ...
    options:
        ...
        excluded_exception:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
```

The sentry documentation https://docs.sentry.io/error-reporting/configuration/?platform=php doesn't even talk about the `excluded_exception` option.

**Comment by Jean85** [comment]
My mistake, that page is about the options available across all SDK in all languages, due to the Unified API approach.

There are a few PHP specific ones, documented in the PHP docs: https://docs.sentry.io/platforms/php/#php-specific-options

**Comment by B-Galati** [comment]
I just had the same issue when was setting up the bundle.

**Comment by B-Galati** [comment]
I used the command `bin/console config:dump-reference sentry` to know more about available options but that is far from ideal from my POV.

**Comment by Jean85** [comment]
What would you suggest as a fix for this issue? Would adding these two links to the readme be enough? PRs are welcome.

**Comment by VincentLanglet** [comment]
@Jean85 In the step https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk

Adding something like 
```md
Every options from the sentry documentation can be used:
- https://docs.sentry.io/error-reporting/configuration/?platform=php
- https://docs.sentry.io/platforms/php/#php-specific-options
```
Would be great indeed

But it's always better with an example:
```yaml
sentry:
    dsn: "https://public:secret@sentry.example.com/1"
    environment: %kernel.environment%
    project_root: %kernel.project_dir%
    excluded_exceptions:
        - PersonalIgnoredException
```
