### ISSUE TITLE
Using sentry as a service

### ISSUE THREAD

**Issue by eerison** [getsentry/sentry-symfony#226]
Is it a good idea implements here `SentryHandler` as Service to use in monolog bundle exemplo:

```
services:
    get_sentry.handler:
        class: SentryHandler
```

```
monolog:
    handlers:
        sentry:
            type: service
            id: get_sentry.handler
```
