### ISSUE TITLE
Integration with monolog reporting errors of all levels

### ISSUE THREAD

**Issue by gliba008** [getsentry/sentry-symfony#227]
Greetings to you all.
I have a problem with integration with monolog. It logs all levels of errors and changing the configuration doesn't help.

# Repro steps:
- Followed this tutorial to the letter: https://github.com/getsentry/sentry-symfony#installation
- Special attention to this
```
// monolog.yaml

sentry:
  type: service
  id: sentry.monolog.handler
  level: error
```
- Added this to my test controller: 
```
public function testMonolog(LoggerInterface $logger)
{
  $logger->error('test');
  return $this->json('ok');
}
```

# Expected behavior
To receive Error with message 'test'

# Real behavior
Received following errors:
- Populated the TokenStorage with an anonymous Token.
- Matched route "{route}".
- Error 'test'
