### ISSUE TITLE
Wrong log level when using the Monolog Handler

### ISSUE THREAD

**Issue by kevin-verschaeve** [getsentry/sentry-symfony#229]
Hi,

When using the Monolog Handler service, the level of reporting is not the one set in the monolog configuration, but always `debug`.

Let's say, I have configured a Monolog handler like it is specified in the README :

```
monolog:
    sentry:
      type: service
      id: sentry.monolog.handler
      level: error 
```

And configured the service :

```
services:
    sentry.monolog.handler:
        class: Sentry\Monolog\Handler
```

This Handler accept 3 arguments : `HubInterface $hub`, `$level = Logger::DEBUG` and `bool $bubble = true`.

As you can see, by default the logger level will be `Logger::DEBUG`, and this level is then passed to the `AbstractProcessingHandler` class from Monolog.

So, even if we set the level into the monolog configuration, this service will override it with its own level, and if we follow the README, it will be `debug`.

The current solution is to change the service definition by precising the level, like so :

```
services:
    sentry.monolog.handler:
        class: Sentry\Monolog\Handler
        arguments:
               $level: 'error'
```

But I don't think that this is the best solution. The best would be to set the service level with the level configured in the monolog configuration file. But I don't know if this is possible.

If not, we should update the README to clarify this point.

What do you think ?
