### ISSUE TITLE
Finger crossed monolog handling not working as expected

### ISSUE THREAD

**Issue by alexander-schranz** [getsentry/sentry-symfony#240]
I'm using monolog (1.25) over the monolog-bundle(3.4) with the default configuration with finger_crossed.

It look like this:

```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        sentry:
            type: service
            id: sentry.monolog.handler
            level: error
```

Sentry handler seems not to filter out the debug logs and create all as issues. Did I configure something wrong?
