### ISSUE TITLE
trigger_error not reporting

### ISSUE THREAD

**Issue by Mika56** [getsentry/sentry-symfony#267]
Hi,

We're currently deprecating some of our actions.
I've added the following code to these actions:
```php
@trigger_error(__METHOD__.' has been deprecated', E_USER_DEPRECATED);
```
I can't understand why, but Sentry won't report these errors, so I've added:
```php
$this->sentry->captureLastError();
```

It works, but for some reason a lot of information is not reported, including the request's URL.

What is the official way to report deprecations? I don't want to use an `Exception` because the action needs to still work.
The bundle's configuration is pretty standard:
```yml
sentry:
    dsn: "%sentry_dsn%"
    options:
        capture_silenced_errors: true # tried adding this, did not change a thing
        default_integrations: true # tried adding this, did not change a thing
        error_types: 'E_ALL' # tried adding this, did not change a thing
        send_default_pii: true
```
