### ISSUE TITLE
Excluded exceptions are being ignored when monolog error handler is enabled

### ISSUE THREAD

**Issue by lkazus** [getsentry/sentry-symfony#273]
I've recently enabled the monolog error handler on a project and realized that the excluded exceptions I configured are being reported. 

After doing some digging, I've found that `Sentry\Monolog\Handler` relies on the `captureEvent` method which does not check if the payload contains an exception and if that exception should be ignored. I was wondering if it was an intended beheavior? If not, I would be happy to submit a PR.

For information this is my config file:
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(SENTRY_ENV)%'
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException

    register_error_listener: false
    monolog:
        error_handler:
            enabled: true
            level: error
```
