### ISSUE TITLE
Sentry monolog handler ignores user context configuration

### ISSUE THREAD

**Issue by Steveb-p** [getsentry/sentry-symfony#275]
Having configuration in YAML as follows:
```
sentry:
  dsn: "https://xxx@xyz.com"
  register_error_listener: false # Disables the ErrorListener
  options:
    send_default_pii: true
    server_name: xyz.com
  monolog:
    error_handler:
      enabled: true
      level: notice
```

`send_default_pii` seems to be ignored. From what I gather scope created by Handler overwrites the one used by `Hub` or the code related to attaching user data is never called.
