### ISSUE TITLE
Symfony service configuration for before_send callback

### ISSUE THREAD

**Issue by nigrampsas** [getsentry/sentry-symfony#336]
Hello, I'm trying to implement the before_send callback functionality in a Symfony 3.4 project. 

I want to filter some events before sending to sentry. 

So I followed the documentation and created the  necessary sentry config in the app/config/config.yml file and included the before_send option like below.

```yaml
sentry:
    dsn: '<dsn-here>'
    options:
        before_send: '@sentry.callback.before_send'
```
I have also created a service class in my project like follows:
```php
<?php

namespace AppBundle\Service;

use Sentry\Event;

class Sentry
{
/**
 * @required 
 */
public function beforeSend(Event $event): ?Event
    {
        switch ($event->getServerName()) {
            case 'server1':
            case 'server2':
            case 'server3':
                 return null;
        }

        return $event;
    }
}
```
The question is how do i declare this the right way in the services.yaml file? The documentation is a bit vague in this point and points to Symfony documentation, but to be honest I'm a bit new to Symfony and an example would make things much easier for me. 

I researched the required annotation in the service class method and says it will be automatically be called when the class instantiates  Here is what I've got so far:
```yaml
services:
  sentry.callback.before_send:
     class: AppBundle\Service\Sentry
```

There is also the setter injection methodology but i'm not sure if its better or if it works in my case.
Is there a better way to do this? How does someone make the beforeSend method of the Service class I made gets called when a sentry event occurs?

**Comment by Jean85** [comment]
The `before_send` expects a `callable` (see https://www.php.net/manual/en/language.types.callable.php), so the service in itself is not good. You have to use either a static call and pass it as a string/array, or use your service as a factory and return a proper `callable`.

**Comment by jmdelehaye** [comment]
I had the same problem and finally managed to fix it.

Here is an example of code that works on symfony 3.4, **could you add it to the documentation?**

```yaml
# config.yml
sentry:
    dsn: '<dsn-here>'
    options:
        before_send: '@sentry.callback.before_send'
```

```yaml
# services.yml
services:
  AppBundle\Tools\Sentry:
    autowire: true

  sentry.callback.before_send:
    autowire: true
    factory: ['AppBundle\Tools\SentryFactory', 'createBeforeSendCallable']
    class: 'AppBundle\Tools\Sentry'
```

```php
# Factory that returns a callable
<?php

declare(strict_types=1);

namespace AppBundle\Tools;

class SentryFactory
{
    public static function createBeforeSendCallable(Sentry $sentry): callable
    {
        return [$sentry, 'beforeSend'];
    }
}
```

```php
# Class that handles the event

<?php

declare(strict_types=1);

namespace AppBundle\Tools;

use Psr\Log\LoggerInterface;
use Sentry\Event;


class Sentry
{
    /** @var LoggerInterface */
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function beforeSend(Event $event): ? Event
    {
        $this->logger->debug(sprintf("Event catched in '%s', id='%s'", __METHOD__, $event->getId()), $event->toArray());

        return $event;
    }
}

```
