### ISSUE TITLE
How to use different message levels (warning/error/...) with Monolog and Sentry ?

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#344]
The documentation explains that I should add
```
sentry:
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
            level: error

monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler
```

With this configuration I assume that only `logger->error` are reported on sentry, as error.

If, instead, I use
```
sentry:
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
            level: warning
```
Both `warning` and `error` will be reported. But they're both reported as error, isn't it ?

What if I want warning to be reported as warning and error reported as error ?
