### ISSUE TITLE
How to capture response / status code?

### ISSUE THREAD

**Issue by kirrg001** [getsentry/sentry-symfony#350]
Hi there!

I am not seeing the HTTP response status code in sentry. How can I configure this to be sent?
I want to display the status code in sentry to configure my alerts as best.

I am using the default setup in Symfony

```
sentry:
  dsn: 'x'
  options:
    environment: '%env(APP_HOST)%'
    release: '%env(APP_RELEASE)%'
    send_default_pii: true
```

Thanks so much!
