### ISSUE TITLE
Release is not sent to sentry

### ISSUE THREAD

**Issue by ChristianVermeulen** [getsentry/sentry-symfony#368]
I have my sentry set up like so:

```yml
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: 'prod'
        release: '%env(APP_VERSION)%'
        send_default_pii: true
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
```

During deploy, in github actions I run a command in capistrano to fill the current release version (obviously I get the current timestamp from capistrano!):

```bash
sed -i.bak 's#%env(APP_VERSION)%#20200917133933#' ./config/packages/prod/sentry.yaml
```

Finally I have verified in the production environment that the release is actually set. I even made sure the replacement is done before the cache warmup.

Yet, still in Sentry no release is available... What am I missing here?

**edit**: I've just noticed a warning in Sentry.

![Screenshot 2020-09-17 at 15 53 36](https://user-images.githubusercontent.com/1062751/93480695-035c8c80-f8fe-11ea-82ff-30dc71980f0b.png)

It suggests the value is empty, however I have confirmed it is not. At least not in the config files on my production servers...

![Screenshot 2020-09-17 at 15 55 02](https://user-images.githubusercontent.com/1062751/93480822-2ab35980-f8fe-11ea-92f0-a6be108777fc.png)

**Comment by Jean85** [comment]
Can you confirm that the framework is properly fetching the config by running `bin/console debug:config sentry` in production? This seems a configuration issue to me.

**Comment by ChristianVermeulen** [comment]
@Jean85 It looks like the config works propperly:
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: prod
        release: 20200930102641
        send_default_pii: true
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
        class_serializers: {  }
        in_app_include: {  }
        in_app_exclude:
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%/vendor'
        integrations: {  }
        prefixes:
            - /itexperts/webreporting/releases/20200930102641
            - /usr/share/php
        tags: {  }
    register_error_listener: true
    listener_priorities:
        request: 1
        sub_request: 1
        console: 1
        request_error: 128
        console_error: 128
        worker_error: 99
    monolog:
        error_handler:
            enabled: false
            level: DEBUG
            bubble: true
    messenger:
        enabled: false
        capture_soft_fails: true
```

However, I just tried to add a prefix as documentend -> `webreporting@20200930102641`.

Now my release is picked up, but only as `webreporting@`. So it seems like Sentry is stripping of timestamps? Is that possible??

**Comment by Jean85** [comment]
@HazAT any pointer here?

**Comment by HazAT** [comment]
@ChristianVermeulen I just tried it and work just fine
![image](https://user-images.githubusercontent.com/363802/98369623-8914d280-2039-11eb-98c7-2bc7dd6268ed.png)

Are you running an old on premise version of Sentry?

**Comment by ChristianVermeulen** [comment]
@HazAT No, we run on the sentry.io using composer package `sentry/sentry:2.5.0` and `sentry/sentry-symfony:3.5.3`. This really baffles me... (and has been for a while now).

**Comment by HazAT** [comment]
@ChristianVermeulen can you please share a link to an issue so I can take a look at your account?

**Comment by ChristianVermeulen** [comment]
@HazAT https://sentry.io/organizations/itexperts/issues/1983676032/?project=5445966&query=is%3Aunresolved&statsPeriod=90d

This is the current configuration on production:
<img width="524" alt="Screenshot 2020-11-06 at 14 23 12" src="https://user-images.githubusercontent.com/1062751/98370922-a21e8300-203b-11eb-9614-b39cabaf61f7.png">

**Comment by HazAT** [comment]
@ChristianVermeulen I guess you are trying it right now
![image](https://user-images.githubusercontent.com/363802/98372559-3d185c80-203e-11eb-8138-6a655d5c0433.png)

Because this seems to work

**Comment by ChristianVermeulen** [comment]
@HazAT hmm weird, in sentry I see all my events without the prefix now, and i can not find any event with the `test`-prefix. I am so confused right now. Or is it normal the prefix is dropped?

**Comment by HazAT** [comment]
when you hover the release you see the full Release name. This feature is used for mobile mostly where the format is `bundleID@version` but for a release you mostly care about the version since the bundleID stays the same.

So I guess we can close the issue.

**Comment by ChristianVermeulen** [comment]
@HazAT On hover I still don't het the prefix.. 

<img width="339" alt="Screenshot 2020-11-06 at 15 05 22" src="https://user-images.githubusercontent.com/1062751/98374813-85854980-2041-11eb-9009-4452fcd26cab.png">

I will update the projects to always include a `prefix@`, but perhaps the documentation should be more clear about this requirement?

**Comment by ChristianVermeulen** [comment]
@HazAT So now, the timestamp is being dropped again all of a suddon. It seems there is some really wonky behavior in parsing the release strings!

<img width="323" alt="Screenshot 2020-11-10 at 14 12 11" src="https://user-images.githubusercontent.com/1062751/98678449-e2914000-235e-11eb-9302-017824745ac9.png">

In case you want a specific event: https://sentry.io/organizations/itexperts/issues/2018215214/?environment=prod&project=5407219

**Comment by mitsuhiko** [comment]
Release strings are not parsed on ingestion. If it shows `emc@` then the client sent `emc@`. The client under normal circumstances only picks up what you configured so I would assume your configuration drops the timestamp somehow. Could it be that you're using variable interpolation to inject a timestamp and the variable is unset?

**Comment by ChristianVermeulen** [comment]
@mitsuhiko not really. I have our `config/packages/prod/sentry.yml` set up with a placeholder: `emc@%env(APP_VERSION)%`.

Then upon release, Capistrano replaces `%env(APP_VERSION)%` with a datatime stamp with a sed command:

```
sed -i.bak 's#%env(APP_VERSION)%##{release_timestamp}#' ./config/packages/prod/sentry.yaml
```

My final config on the production server looks like this:

<img width="522" alt="Screenshot 2020-11-10 at 15 17 38" src="https://user-images.githubusercontent.com/1062751/98685626-e4abcc80-2367-11eb-8376-6fdd259e1074.png">

From that moment on, it is just plain simple configuration. This happens before the cache warmup command, so in cache all should be well. As you can see confirmed in my previous comment here: https://github.com/getsentry/sentry-symfony/issues/368#issuecomment-701306425

**Comment by ChristianVermeulen** [comment]
@HazAT / @mitsuhiko Any progress on this? I now have 2 separate projects which both show this problem :(.

**Comment by ChristianVermeulen** [comment]
So, just to do a bit more debugging I tried to include [Capistrano-Sentry](https://github.com/codeur/capistrano-sentry) to make sure the releases are properly notified through the api. I also wanted to make sure I have checked everything on my end. Since capistrano symfony uses the commit hash for release, I have also adopted this.

This is my current config according to `bin/console debug:config sentry`:
```
Current configuration for extension with alias "sentry"
=======================================================

sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: prod
        release: bf246250b2fe98a33981d303f6bb00dc7b87d303
        send_default_pii: true
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
        class_serializers: {  }
        in_app_include: {  }
        in_app_exclude:
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%/vendor'
        integrations: {  }
        prefixes:
            - /itexperts/emc/releases/20201210103440/vendor/pear/pear_exception
            - /itexperts/emc/releases/20201210103440/vendor/pear/console_getopt
            - /itexperts/emc/releases/20201210103440/vendor/pear/pear-core-minimal/src
            - /itexperts/emc/releases/20201210103440/vendor/pear/ole
            - /itexperts/emc/releases/20201210103440
            - /usr/share/php
        tags: {  }
    register_error_listener: true
    listener_priorities:
        request: 1
        sub_request: 1
        console: 1
        request_error: 128
        console_error: 128
        worker_error: 99
    monolog:
        error_handler:
            enabled: false
            level: DEBUG
            bubble: true
    messenger:
        enabled: false
        capture_soft_fails: true
```

Looks good to me. When looking in the sentry releases, I successfully see the release created and available:

![Screenshot 2020-12-10 at 11 56 01](https://user-images.githubusercontent.com/1062751/101763162-b3e1c300-3ade-11eb-92c7-bba389fc4968.png)

So I go ahead and trigger an exception in our app, which  is picked up by sentry, yet still with the óld (and incorrect) release tag! https://sentry.io/organizations/itexperts/issues/2083003853/events/de679a429bc74eef80ca07a3bd10fd6a/?project=5407219&query=is%3Aunresolved

I have verified:
- Last effective deploy on server: 2020-12-10 10h34 (UTC)
- Release creation: 2020-12-10 10h36 (UTC)
- [Last events with old tag](https://sentry.io/organizations/itexperts/issues/2083003853/events/?project=5407219): 2020-12-10 10h57 (UTC)
- Configuration on webserver confirmed

So I'm pretty much out of options on my end here guys. One thing seems clear to me, funky things áre happening on the Sentry side. Be it a caching issue, parsing issue, I don't know...
