### ISSUE TITLE
How to configure level based on environment variable (monolog integration)

### ISSUE THREAD

**Issue by FallDi** [getsentry/sentry-symfony#384]
https://github.com/getsentry/sentry-symfony#optional-use-monolog-handler-provided-by-sentrysentry-available-since-320

Is it possible to configure level, based on environment variable?
```
sentry:
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
#            level: error
             level: "%env(LOG_LEVEL)%"
```

Currently it fails with `Incompatible use of dynamic environment variables "LOG_LEVEL" found in parameters.`

Such availability will really useful.

Similar ability was implemented in Monolog bundle recently https://github.com/symfony/monolog-bundle/commit/541e6e56a0b114ddf1dbd08c7392337677b48cae

Following config will be perfect solve such issue
```
parameters:
    sentry.level: '%env(LOG_LEVEL)%'

sentry:
    dsn: "%env(SENTRY_DSN)%"
    options:
        environment: "%kernel.environment%"
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
            level: "%sentry.level%"
```
