### ISSUE TITLE
Absolute paths instead of relative paths since 4.0

### ISSUE THREAD

**Issue by ruudk** [getsentry/sentry-symfony#431]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Symfony 4.0

### Steps to Reproduce

Since upgrading to Symfony 4.0 I noticed that reported paths are no longer relative to the `project_dir` but absolute paths like this:
<img width="489" alt="Screenshot 2021-01-27 at 08 44 53@2x" src="https://user-images.githubusercontent.com/104180/105959289-002b9700-607c-11eb-913d-cd5aca140df6.png">

I searched the docs but couldn't find anything related to this. 

### Expected Result

Relative path to `%kernel.project_dir%`.

**Comment by Jean85** [comment]
@ste93cry are you using 4.0 in prod? Do you have the same issue?

**Comment by Jean85** [comment]
I'm using 3.5.2 in prod with default options and I do NOT get the full path. Hence, it's probably due to 4.0.

**Comment by ste93cry** [comment]
>@ste93cry are you using 4.0 in prod

Not yet

**Comment by ruudk** [comment]
I tried this config in production but it doesn't solve the problem:
```yaml
sentry:
    options:
        in_app_include:
            - '%kernel.project_dir%'
```

**Comment by Jean85** [comment]
`in_app_exclude` has these defaults: https://github.com/getsentry/sentry-symfony/blob/24b1dace366127a665b1cd1f6ed53e7dc2921ead/src/DependencyInjection/Configuration.php#L99-L101

So it could be duplicated, that's normal.

**Comment by mbabker** [comment]
If I'm following right, the issue is the prefixes option isn't being set, and you'll need this to make relative paths again:

```yaml
sentry:
    options:
        prefixes:
            - '%kernel.project_dir%'
```

**Comment by ruudk** [comment]
@mbabker Thanks. I'm going to try that out next week and reply back.

**Comment by ruudk** [comment]
```yaml
sentry:
    options:
        prefixes:
            - '%kernel.project_dir%'
```

seems to be the solution.

However, I think I need to add a `/` suffix because it now looks like this:
<img width="270" alt="CleanShot 2021-02-01 at 10 11 45@2x" src="https://user-images.githubusercontent.com/104180/106437781-e91ee780-6475-11eb-9dc4-45715de7ec2c.png">

I think it would make more sense if Sentry automatically truncated starting slashes.
