### ISSUE TITLE
Causes too many database connections via behat.

### ISSUE THREAD

**Issue by iaicam** [getsentry/sentry-symfony#436]
### Environment

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
3.10 SDK
bundle 4.0.1

### Steps to Reproduce

1. `composer require sentry/sentry-symfony`
2. Accept recipe
3. add in the following sentry config 
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
services:

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException
```
4. Commit and push to bitbucket
5. Bitbucket pipeline runs.
6. 
### Expected Result

Behat passes normally

### Actual Result

Behat fails half way through with every test resulting in the same error

```
  ╳  PDOException: SQLSTATE[08006] [7] FATAL:  sorry, too many clients already in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38
  ```
### Note

It may be useful to know I have two dbal connections one for MySQL and one for TimescaleDB which uses the postgres driver and it's the timescaledb that is failing.

**Comment by iaicam** [comment]
This also happens on 3.5.8.

**Comment by Jean85** [comment]
The issue seems to be raised from PDO itself, since `PDOConnection.php:38` is a call to `parent::__construct`. Doesn't seem to me something related to Sentry, but maybe only triggered by its installation.

Maybe you have some connection limitation in your DB?

**Comment by iaicam** [comment]
The connection issue will come from Postgres/Timescale. However, it is only caused when I installed the sentry bundle. Literally, the only change made was enabling the sentry bundle and the error arrived and when I removed it the error left. It seems logical that somehow the sentry bundle is interacting with Doctrine/Dbal/PDO in a way that causes it to lose a connection and regenerate a new one.

**Comment by Jean85** [comment]
That's not the only possible interaction; adding a new bundle could heavily shape how the DI container is dumped, hence creating the possibility for a trigger (but not a direct cause) of this issue.

Citing a fast search: https://www.enterprisedb.com/blog/postgresql-pgpool-connection-pool-database-load

> Simply put, this error appears when the number of clients connected to the database exceeds the concurrent limit max_connections defined in the postgresql.conf file.

So, you're connecting too many times. Are you sure that your container is not over-instantiating its client multiple times? Or not sharing the instances?

**Comment by iaicam** [comment]
> That's not the only possible interaction; adding a new bundle could heavily shape how the DI container is dumped, hence creating the possibility for a trigger (but not a direct cause) of this issue.

No that is the only interaction. Well, I did have to raise the PHP memory limit because of the memory usage caused by this bundle. Oh, and I had to manually add a dependency this bundle has. Overall, I tried to use this bundle and encountered 3 separate issues. The bug report is legit. I understand why you firmly believe this bundle is not the cause because it's completely nuts but sadly it is.

![image](https://user-images.githubusercontent.com/47746941/107247614-beaeca80-6a31-11eb-9f9f-261ed1777072.png)

**Comment by Jean85** [comment]
I'm saying that the bundle is not the root cause, but I agree that it's triggering the issue. I'm convinced that it's not the root cause since our code has no other way to interact with a database connection, so it's something a lot more complex that "your bundle has a bug". You can understand my scepticism since this is a very strange bug report, and this bundle is widely used, with no reports of such memory bloats up until now.

Please keep in mind that this is an open source library and we're volunteers, not paid employees. And without further details on your end, we're unable to help further.

**Comment by iaicam** [comment]
> Please keep in mind that this is an open source library and we're volunteers, not paid employees. And without further details on your end, we're unable to help further.

I was about to ask. If this bundle is actually supported by Sentry since the responses have been coming from developers other than them. Since this is an official bundle, I was under the impression that it is part of the service they're selling. This is meant for the company and not you guys, but I find it really bad that Sentry is relying on unpaid help for their customer support. Which this basically is.

**Comment by ste93cry** [comment]
Noone ever reported this issue before. This is not to say there is no bug, there may very well be one (here or in the main SDK), but without further information it's simply impossible to track down the issue, and given that the issue is involving at least one element that is not reproducible without a test case (e.g. a repo with a project that reproduces the issue), I don't understand how you expect us (or the Sentry folks, in case) to help you further

>I had to manually add a dependency this bundle has

I'm pretty sure you're issue is the same as #379, which is not a fault of this bundle but rather an unfortunate consequence of having installed the `SensioFrameworkExtraBundle` bundle which expects the `nyholm/psr7` package to be installed without requiring it in its `composer.json` when the `HttpFoundationFactoryInterface` interface exists. This problem causes applications to break as soon as something else requires `symfony/psr-http-message-bridge`, which is the package providing that interface, and it's gonna be solved in version `6.0` of that bundle.

>I find it really bad that Sentry is relying on unpaid help for their customer support

Note: I'm talking as a contributor, so these are my thoughts. Paid support can be contacted on the Sentry website, if you need it. I don't think GitHub is the right place to expect this kind of support, but rather a place where to discuss about bugs and maybe contribute back to the project.

**Comment by iaicam** [comment]
I'll add my doctrine.yaml to help you guys.

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            timescale:
                url: '%env(resolve:TIMESCALE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        connection: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        resolve_target_entities:
            HumblyArrogant\Underpin\User\Entity\UserInterface: App\Entity\User
            HumblyArrogant\Underpin\User\Entity\TeamInterface: App\Entity\Team
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Underpin_User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/humblyarrogant/underpin-bundle/src/User/Entity'
                prefix: 'HumblyArrogant\Underpin\User\Entity'
                alias: Underpin_User
            Underpin_BackOffice:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/humblyarrogant/underpin-bundle/src/BackOffice/Entity'
                prefix: 'HumblyArrogant\Underpin\BackOffice\Entity'
                alias: Underpin_BackOffice
```

The customer entities from the bundles only use MySQL so won't use the pgsql driver which is failing.

> Note: I'm talking as a contributor, so these are my thoughts. Paid support can be contacted on the Sentry website, if you need it. I don't think GitHub is the right place to expect this kind of support, but rather a place where to discuss about bugs and maybe contribute back to the project.

This is an **official** and therefore supported the project of a company that I **was going to pay money** to. It is required as part of the **onboarding** process. It does not seem unreasonable to expect at least on employee to swing by on an onboarding error.  This is basically part of the person's first experience with Sentry a **for-profit company** and if the experience is that they will have to rely on the kindness of strangers to help them onboard to a company that they will be paying money to, it's not good. First impressions matter. If this was an unofficial bundle, it would be completely different, but this is not. I even checked the license to see if it was copyrighted to other people but it's copyrighted to a for-profit company. This is a technical product and **requires technical onboarding**, therefore, technical support and sales will come via its GitHub support system. This is software from a for-profit company. So I feel like the whole you can pay for support when I was literally going to pay them and I was doing the onboarding trial, is just as bad as Sentry not having a single paid employee comment on this. Especially since the CTO @dcramer has visited this thread. **Literally, the CTO has swung by and didn't say anything or provide any support. As I said, this is basically customer support you're doing for free, for a for-profit company.**
