### ISSUE TITLE
trace/performance is not being collected/pushed

### ISSUE THREAD

**Issue by douglasjam** [getsentry/sentry-symfony#442]
I'd like to enable traces with my Symfony application, but I tried and dug into the bundle, but couldn't manage to make it work, simply nothing appears on the website.

Issues/exceptions are being collected properly but traces not.

Do I need to do some extra configuration? How can I debug why it doesn't work properly? What is missing? I added breakpoints in the `isTracingEnabled` and `startTransaction` but doesn't go there.

### Environment
symfony 5.2
sentry SaaS
php 8.02
sentry/sentry-symfony 4.0

### Steps to Reproduce

I have the following configuration

packages/sentry.yaml
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: true
    options:
        traces_sample_rate: 1.0
```

services.yaml
```
    Sentry\Monolog\Handler:
        public: true
        arguments:
            $level: !php/const Monolog\Logger::WARNING
```
