### ISSUE TITLE
 Uncaught Error: Class Sentry\Options not found

### ISSUE THREAD

**Issue by eerison** [getsentry/sentry-symfony#459]
### Dev

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

basically after try to update sentry-symfony, I'm getting an error.
`composer req sentry/sentry-symfony:^4.0 -W` 

### Actual Result

```
Creating myprofile_php_run ... done
./composer.json has been updated
Running composer update sentry/sentry-symfony --with-all-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.2.*"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
96 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your JavaScript dependencies!
Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#4597
!!    #message: """
!!      Attempted to load class "Options" from namespace "Sentry".\n
!!      Did you forget a "use" statement for e.g. "Symfony\Flex\Options" or "Symfony\Component\OptionsResolver\Options"?
!!      """
!!    #code: 0
!!    #file: "./vendor/sentry/sentry-symfony/src/DependencyInjection/Configuration.php"
!!    #line: 88
!!    trace: {
!!      ./vendor/sentry/sentry-symfony/src/DependencyInjection/Configuration.php:88 { …}
!!      ./vendor/symfony/config/Definition/Processor.php:50 { …}
!!      ./vendor/symfony/dependency-injection/Extension/Extension.php:111 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/ConfigurableExtension.php:35 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:736 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:541 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:780 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:121 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:166 { …}
!!      ./bin/console:43 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!        arguments: {
!!          $input: Symfony\Component\Console\Input\ArgvInput {#5 …}
!!        }
!!      }
!!    }
!!  }
!!  2021-03-04T19:56:28+00:00 [critical] Uncaught Error: Class 'Sentry\Options' not found
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

- It's the pull request: https://github.com/eerison/myprofile/pull/375/files
- Symfony 5.2

**Comment by eerison** [comment]
I'm closing this issue because I resolved it 

- removing
```
 "replace": {
        "sentry/sdk": "*"
    }
```

- adding
```
composer require pugx/sentry-sdk
```

**Comment by stayallive** [comment]
The regular `sentry/sdk` package uses the Symfony HTTP client now so I'm not sure you still need any of these "workarounds". 

Can you try just requiring `sentry/sentry-symfony` (no `sentry/sdk` or `pugx/sentry-sdk`)?

I'm not sure that package is needed anymore (we used to have Guzzle but that is no longer the case).

**Comment by eerison** [comment]
Hi @stayallive I removed the `pugx/sentry-sdk` but I get this error:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 54:
!!                                                                                 
!!    Cannot autowire service "Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFacto  
!!    ry": argument "$serverRequestFactory" of method "__construct()" references   
!!    interface "Psr\Http\Message\ServerRequestFactoryInterface" but no such serv  
!!    ice exists. Did you create a class that implements this interface?           
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
xmb00559:myprofile erison.silva$ 

```

composer.json
```yaml
"require": {
        "php": "^8.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/annotations": "^1.11",
        "doctrine/doctrine-bundle": "^2.2",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/orm": "^2.7",
        "presta/sitemap-bundle": "^2.1",
        "sensio/framework-extra-bundle": "^5.6",
        "sentry/sentry-symfony": "^4.0",
        "stof/doctrine-extensions-bundle": "dev-master",
        "symfony/apache-pack": "^1.0",
        "symfony/console": "^v5.2",
        "symfony/dotenv": "v5.2",
        "symfony/expression-language": "v5.2",
        "symfony/flex": "^1.3",
        "symfony/form": "v5.2",
        "symfony/framework-bundle": "v5.2",
        "symfony/http-client": "v5.2",
        "symfony/mailgun-mailer": "v5.2",
        "symfony/monolog-bundle": "^3.5",
        "symfony/proxy-manager-bridge": "^v5.2",
        "symfony/security-bundle": "v5.2",
        "symfony/translation": "v5.2",
        "symfony/twig-pack": "^1.0",
        "symfony/validator": "v5.2",
        "symfony/webpack-encore-bundle": "^1.7",
        "symfony/yaml": "^v5.2",
        "symfonycasts/reset-password-bundle": "^1.2",
        "symfonycasts/verify-email-bundle": "^1.2",
        "transloadit/php-sdk": "^2.1"
    },
```

**Comment by eerison** [comment]
and when I install the `sentry/sentry-symfony`

has added `psr_http_message_bridge.yaml` with

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'

    Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: null
    Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory: null

    # Uncomment the following line to allow controllers to receive a
    # PSR-7 server request object instead of an HttpFoundation request
    #Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver: null

    # Uncomment the following line to allow controllers to return a
    # PSR-7 response object instead of an HttpFoundation response
    #Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener: null

```

is that right?
