### ISSUE TITLE
Not connecting issues (errors) with performance traces

### ISSUE THREAD

**Issue by askold123** [getsentry/sentry-symfony#462]
### Environment

Using https://github.com/getsentry/sentry-symfony with Symfony 5.2

### Steps to Reproduce

Enable tracing as in sentry doc https://docs.sentry.io/platforms/php/guides/symfony/performance/#custom-instrumentation using this options in config:
```yaml
sentry:
  dsn: "%env(SENTRY_DSN)%"
  options:
    traces_sample_rate: 1.0
    sample_rate: 1
```

### Expected Result

Exceptions are connected with transaction as it shown in this video https://youtu.be/sA1rED-zb6w?t=375

### Actual Result

Exceptions are sent in separate event and are not connected to transaction in Sentry UI.
