### ISSUE TITLE
How to use traces_sampler ?

### ISSUE THREAD

**Issue by ldath** [getsentry/sentry-symfony#470]
Hello, 

My problem is that I can't find documentation how to use traces_sampler which is finally available.

My `sentry.yml` 
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        # release: '%env(VERSION)%' #your app version
        traces_sampler: 'App\Service\MyTracesSampler'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
```
My `services.yml`
```
services:

...

    # Sentry
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - 'Symfony\Component\Routing\Exception\ResourceNotFoundException'
                    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                    - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
                    - 'Symfony\Component\Security\Core\Exception\AuthenticationException'

    App\Service\MyTracesSampler:
        calls:
            - method: getTracesSampler
```
My `MyTracesSampler.php`
```
<?php


namespace App\Service;

use Symfony\Component\HttpFoundation\RequestStack;


class MyTracesSampler
{
    protected $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function getTracesSampler(): float {
        $request = $this->requestStack->getCurrentRequest();

        if ($request->getRequestUri() == '/echo') {
            // Used by health check
            return 0.0;
        }
        // Sample rate for all other transactions
        return 1.0;
    }
}
```

I'm ending with Error:
> The option "traces_sampler" with value App\Service\MyTracesSampler is expected to be of type "null" or "callable", but is of type "App\Service\MyTracesSampler".

I was trying to return callable array in this function but I ends with similar error just saying that array returned not callable.

What I'm doing wrong?

**Comment by Jean85** [comment]
Since you're passing a service for that field, you need to define it with a factory that return the callable. This is valid for any option that expects a callable.

So something like this:
```yaml
sentry:
    options:
        traces_sampler: 'my_sentry_tracer_sampler'

services:
  my_sentry_tracer_sampler:
    factory: ['@\App\Service\MyTracesSampler', 'getTracesSampler']
```
```php
<?php

namespace App\Service;

use Symfony\Component\HttpFoundation\RequestStack;

class MyTracesSampler
{
    protected $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function getTracesSampler(): callable
    {
        $request = $this->requestStack->getCurrentRequest();
        return function(SamplingContext $context) use ($request): float {
            if ($request->getRequestUri() == '/echo') {
                // Used by health check
                return 0.0;
            }
            // Sample rate for all other transactions
            return 1.0;
        }
    }
}
```
Keep in mind that you have a `SamplingContext` as input that you can leverage.
