### ISSUE TITLE
502 (Bad Gateway) instead of 400 (Bad Request)

### ISSUE THREAD

**Issue by rybindmitriy** [getsentry/sentry-symfony#473]
### Environment
Symfony 5.2.6
PHP 8.0.3
Sentry 4.0.3

### Steps to Reproduce

sentry.yaml
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
```

services.yaml
```
Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - App\Exception\BadRequestValidationHttpException
```

ExceptionSubscriber.php

```php
final class ExceptionSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::EXCEPTION => [
                'onKernelException',
            ],
        ];
    }

    public function onKernelException(ExceptionEvent $exceptionEvent): void
    {
        $exception = $exceptionEvent->getThrowable();

        if ($exception instanceof BadRequestValidationHttpException) {
            $response =
                new JsonResponse(
                    [
                        'errors' => $exception->getErrors(),
                    ],
                    Response::HTTP_BAD_REQUEST,
                );

            $exceptionEvent->setResponse($response);
        }
    }
}
```

### Expected Result

Response with 400 (Bad Request) response code

### Actual Result

502 (Bad Gateway)

But if I change Response::HTTP_BAD_REQUEST to Response::HTTP_CONFLICT or Response::HTTP_FORBIDDEN i get response with right status code: 409 and 403 accordingly
