### ISSUE TITLE
Deprecation warnings in 4.1.0

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#483]
### Environment

How do you use Sentry?
self-hosted

Which SDK and version?

sentry-symfony 4.1.0
symfony 5.2.6

### Steps to Reproduce

Symfony reports a couple of deprecation warnings

```
1x: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.

  1x: The "Sentry\State\HubAdapter::captureMessage()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

  1x: The "Sentry\State\HubAdapter::captureException()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

  1x: The "Sentry\State\HubAdapter::captureLastError()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

```

### Expected Result

no warnings

**Comment by Jean85** [comment]
The last three deprecations are fixed in https://github.com/getsentry/sentry-php/pull/1206, and will be released in the next patch version of `sentry/sentry`.

The first one instead is tricky, and I'm not sure we can overcome it... DBAL is pretty entangled now.

**Comment by man-htsts** [comment]
```
bin/console doctrine:migrations:list -q
2021-09-20T21:12:46+03:00 [info] User Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.

```
How to suppress this error message?

**Comment by Jean85** [comment]
We're trying something more with #553, but it's possible that those deprecations will never go away since we have to support both DBAL v2 & v3 at the same time.

**Comment by man-htsts** [comment]
But how can i suppress this message from output, when i call `bin/console doctrine:migrations:list`?
Is there any way to hide it from output?

**Comment by Jean85** [comment]
That's due to Symfony, not us, you need to check their docs.

**Comment by man-htsts** [comment]
I don't deeply understand how errors are handled, but i think that it's an error(notice) inside error handler, and that is why it is not handled by other error handlers and go to STD_ERR in console.

```
monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
        php_info_filter:
            type: filter
            handler: php_info
            accepted_levels: ["info"]
            channels: ["php"]
            bubble: false
        php_info:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.php_info.log"
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

```

**Comment by ste93cry** [comment]
I bet it won't, but can you please try updating to `4.2.3` and see if it solves the problem?

**Comment by Jean85** [comment]
> I don't deeply understand how errors are handled, but i think that it's an error(notice) inside error handler, and that is why it is not handled by other error handlers and go to STD_ERR in console.

It's a deprecation, so it's handled like that. Since Symfony 5.1+, there's a dedicated channel: https://github.com/symfony/recipes/blob/master/symfony/monolog-bundle/3.7/config/packages/prod/deprecations.yaml

**Comment by nspyke** [comment]
> I bet it won't, but can you please try updating to `4.2.3` and see if it solves the problem?

Hi @ste93cry. Upgrading to 4.2.3 has removed the deprecation warning. I was on 4.2.2 previously.

**Comment by ste93cry** [comment]
I think that the deprecation gone because you also upgraded the `doctrine/dbal` package to `3.x`, otherwise it doesn't make sense because we're still implementing the old interface

**Comment by iker-barriocanal** [comment]
IIUC, the warnings should be gone in the latest `4.2.3` release, right? If yes, can we close the issue?

**Comment by ste93cry** [comment]
I just checked some projects I work on and I definitely still see the deprecation about the `ExceptionConverterDriver` interface. Unfortunately, the issue is not that easy to solve because we have to implement all interfaces to avoid failures with `instanceof` checks 😞

**Comment by Tofandel** [comment]
Still seing deprecations in 4.2.3
```txt
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
2022-02-02T18:39:03+00:00 [info] User Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" class implements "Doctrine\DBAL\Driver\ServerInfoAwareConnection" that is deprecated The methods defined in this interface will be made part of the {@see Driver} interface in the next major release.
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
```

**Comment by wimwinterberg** [comment]
hi ~ I also encounter the deprecation messages on the console. What I found out was that when I enabled Sentry as a logger DebugHandlersListener of SF was called after Sentry ErrorHandler was initialized. Therefore the following code

```php
$handler = set_exception_handler('var_dump');
$this->earlyHandler = \is_array($handler) ? $handler[0] : null;
restore_exception_handler();
```
sees the Sentry ErrorHandler instead of the Symfony ErrorHandler, what then results in the Logger not properly being setup for the ErrorHandler (which is normally done in DebugHandlersListener ::configure), which then results in the default BufferingLogger to be used for the deprecation message which are outputted at the end.

As a fix for this I used Sentry logger using the old behaviour using monolog.type=service instead of sentry and the lazy loaded that services. This way DebugHandlersListener __constructor is caller before Sentry changes the error_handler.

```yml
monolog:
  handlers:
    sentry:
      type: service
      id: App\Sentry\MonologHandler
```

see: https://symfony.com/doc/current/service_container/lazy_services.html
```yml
  App\Sentry\MonologHandler:
    lazy: true
    public: true
    arguments:
      $hub: '@Sentry\State\HubInterface'
      $level: !php/const Monolog\Logger::ERROR
```

I hope this helps
