### ISSUE TITLE
Issue with custom error template rendering with 500 error

### ISSUE THREAD

**Issue by adrienfr** [getsentry/sentry-symfony#485]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

1. Migrate from "sentry/sentry-symfony:4.0" to "sentry/sentry-symfony:4.1"
2. Env is prod (and debug is false)
3. Monolog enabled
4. Generate a 500 error

### Expected Result

This should display my custom error page (templates/bundles/TwigBundle/Exception/error.html.twig)

### Actual Result

The displayed error is the generic one :
<img width="606" alt="Capture d’écran 2021-04-20 à 12 47 24" src="https://user-images.githubusercontent.com/4313077/115383809-916f5d00-a1d6-11eb-8654-c06fd2858836.png">

It seems that `TwigErrorRenderer` is not called anymore.

404 errors are not concerned, the custom error page (templates/bundles/TwigBundle/Exception/error404.html.twig) is correctly displayed (as it was before on "sentry/sentry-symfony:4.0").

Here is my configuration :

**prod/sentry.yml**
```yaml
sentry:
    dsn: "%sentry.dsn%"
    options:
        environment: "%kernel.environment%"
        send_default_pii: true
```

**Comment by ste93cry** [comment]
Can you please try setting `sentry.tracing.twig.enabled` to `false`?

**Comment by adrienfr** [comment]
This doesn't change anything but it does when setting `sentry.tracing.enabled` to false or :
```yaml
    tracing:
        twig:
            enabled: true
        cache:
            enabled: true
        dbal:
            enabled: false
```
The issue seems to be with dbal tracing instead
