### ISSUE TITLE
The bundle v4 logs deprecated warnings

### ISSUE THREAD

**Issue by alex-pravdin-sn** [getsentry/sentry-symfony#505]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-symfony package v4.1.1

### Steps to Reproduce

I have the following Sentry configuration in my app where I want to log to Sentry errors only:
```
sentry:
  register_error_listener: false # Disables the ErrorListener to work thru the Monolog handler
  dsn: '%sentry_dsn%'
  messenger:
    enabled: true # flushes Sentry messages at the end of each message handling
    capture_soft_fails: true # captures exceptions marked for retry too
  options:
    environment: '%kernel.environment%'
    integrations:
      - 'Sentry\Integration\IgnoreErrorsIntegration'

monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface

services:
  _defaults: # Defaults for THIS file only
    autowire: true
    autoconfigure: true
    public: false

  Monolog\Processor\PsrLogMessageProcessor:
    tags: { name: monolog.processor, handler: sentry }

  Sentry\Integration\IgnoreErrorsIntegration:
    arguments:
      $options:
        ignore_exceptions: #exclude validation errors
          - Symfony\Component\Security\Core\Exception\AccessDeniedException

  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory:

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'

  Http\Factory\Guzzle\ServerRequestFactory:

  Psr\Http\Message\ServerRequestFactoryInterface: '@Http\Factory\Guzzle\ServerRequestFactory'

  Http\Factory\Guzzle\UploadedFileFactory:

  Psr\Http\Message\UploadedFileFactoryInterface: '@Http\Factory\Guzzle\UploadedFileFactory'

  Http\Factory\Guzzle\ResponseFactory:

  Psr\Http\Message\ResponseFactoryInterface: '@Http\Factory\Guzzle\ResponseFactory'

  Http\Factory\Guzzle\StreamFactory:

  Psr\Http\Message\StreamFactoryInterface: '@Http\Factory\Guzzle\StreamFactory'

```

### Expected Result

Only errors logged.

### Actual Result

I see a lot of `deptecated` and `notice` errors like these:

![image](https://user-images.githubusercontent.com/61450549/118429186-12554200-b70c-11eb-8636-10047b0b3bf4.png)

![image](https://user-images.githubusercontent.com/61450549/118429222-25681200-b70c-11eb-9a0b-d2c5cbb02366.png)

What I'm doing wrong?

**Comment by Jean85** [comment]
Do you have other Monolog handlers configured? Those work in cascade, that may be the culprit.

**Comment by alex-pravdin-sn** [comment]
Here is the other monolog handler config:

```
monolog:
  handlers:
    console:
      type: console
      channels: [ "!event", "!doctrine", "!console" ]
      process_psr_3_messages: true
```

**Comment by Jean85** [comment]
Oh, but I just noticed! You're using the Monolog's handler, the one provided by MonologBundle, not ours!

To use ours, you'll need this service definition:

```yaml
services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
            $bubble: false
```
