### ISSUE TITLE
Performance Monitoring Problem

### ISSUE THREAD

**Issue by Evoluti0n** [getsentry/sentry-symfony#509]
### Environment

How do you use Sentry: on-premise Sentry 20.9.0 bb3d590

### Steps to Reproduce

1. Update sentry/sentry-symfony to 4.1.1
2. enable tracing
3. Nothing happens

Hello, 
as far as I understand, the performance monitoring works with version 4.1, but after the update nothing happens. 
Two questions 
1. Is it possible to test the performance monitoring explicitly?
2. besides the settings in the .yml must be done more? 

Thanks a lot

sentry.yml
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    tracing:
        enabled: true
        dbal: # DB queries
            enabled: true
        twig: # templating engine
            enabled: true
```

PS: Error messages pushed successfully.
