### ISSUE TITLE
Configuration options have no effect

### ISSUE THREAD

**Issue by lmeyer1** [getsentry/sentry-symfony#534]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?

Currently installed:
- symfony/monolog-bundle: 3.5.0
- sentry-symfony: 3.5.4
- symfony: 3.4.37

The application is Prestashop 1.7.7.4 https://github.com/PrestaShop/PrestaShop

### Steps to Reproduce

1. I configured sentry in `config_dev.yml`
```

monolog:
    handlers:
        main:
            type:   stream
            path:   '%env(PS_LOG_OUTPUT)%'
            level:  debug
            channels: ["!event"]
        sentry:
            type: service
            id: Sentry\Monolog\Handler
sentry:
    dsn: "https://....ingest.sentry.io..."
    options:
        environment: dev
        release: !php/const SENTRY_RELEASE
        error_types: "E_ALL & ~E_USER_DEPRECATED"
        capture_silenced_errors: false
```

The options are applied:

$ php bin/console debug:config sentry

Current configuration for extension with alias "sentry"
=======================================================

```
sentry:
    dsn: '...ingest.sentry.io...'
    options:
        environment: dev
        release: '20210713154815'
        error_types: 'E_ALL & ~E_USER_DEPRECATED'
        capture_silenced_errors: false
        class_serializers: {  }
        in_app_include: {  }
        in_app_exclude:
            - (...)
        excluded_exceptions: {  }
        integrations: {  }
        prefixes:
            - (...)
        tags: {  }
    register_error_listener: true
    listener_priorities:
        request: 1
        sub_request: 1
        console: 1
        request_error: 128
        console_error: 128
        worker_error: 99
    monolog:
        error_handler:
            enabled: false
            level: DEBUG
            bubble: true
    messenger:
        enabled: false
        capture_soft_fails: true
```

But they have not the accounted effect. Silenced errors are still logged, as are user deprecations.

### Expected Result

Despite `capture_silenced_errors: false`, Errors like *filemtime(): stat failed* are logged for `if (!@filemtime($fileUri) || @filesize($fileUri) === 0) {`. I would expect this error to go unnoticed.

Despite `error_types: 'E_ALL & ~E_USER_DEPRECATED'` , errors like *Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.* are logged for below code, where we have a user deprecation.

    @trigger_error(
        'Creating ' . self::class . ' without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.',
        E_USER_DEPRECATED
    );

### Actual Result

The settings are applied, but do not have the expected effect. Silenced errors are still logged, as are user deprecations.
