### ISSUE TITLE
Bumping from Symfony 4.4 to Symfony 5.3 stops Sentry to work

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#546]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"sentry/sentry-symfony": "4.2.*",

### Steps to Reproduce

I bumped symfony version from 4.4 to 5.3 and I'm not receiving Sentry errors anymore.
I don't really know how to debug this, I bump all the Symfony dependency and `symfony/contracts`

My config is 
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    messenger:
        enabled: true
        capture_soft_fails: false
    tracing:
        enabled: true
        cache:
            enabled: true
        dbal:
            enabled: false # https://github.com/getsentry/sentry-symfony/issues/488
        twig:
            enabled: true
    options:
        sample_rate: 1.0
        traces_sample_rate: 1.0
        integrations:
            - Sentry\Integration\IgnoreErrorsIntegration

services:
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
            $bubble: true

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\Messenger\Exception\HandlerFailedException           # Handled by messenger integration
                    - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException       # 403
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException           # 404
                    - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException   # 405
                    - Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException # 412
                ignore_tags:
                    route: assurancevie_legacy_default_index
```
With 
```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        sentry:
            type: service
            id: Sentry\Monolog\Handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
```

### Expected Result

I changed nothing from the config (but I'm not sure the purpose of everything) so I would expect that it works the same.

### Actual Result

Nothing is sent anymore on Sentry when I'm getting a 500.
