### ISSUE TITLE
Traces sampling does not work when using SENTRY_DSN environment variable

### ISSUE THREAD

**Issue by bijsterdee** [getsentry/sentry-symfony#569]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry/sentry 3.3.3

### Steps to Reproduce
I set the following in sentry.yaml:

```yaml
sentry:
  register_error_listener: false
  options:
    traces_sample_rate: 1.0
```

I use the SENTRY_DSN environment variable.

### Expected Result

incoming transactions into Sentry

### Actual Result

There are no transactions showing up into Sentry. When I add the dsn to sentry.yaml it starts working. But I want to use the SENTRY_DSN environment variable.
