### ISSUE TITLE
`sentry.options.traces_sample_rate`- is not configurable with dotenv vars

### ISSUE THREAD

**Issue by much-rebel** [getsentry/sentry-symfony#572]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-symfony: 4.2.4

### Steps to Reproduce

Consider following configurations...

#### sentry.yaml #1
```
parameters:
    env(SENTRY_TRACE_SAMPLE_RATE): 0

sentry:
    options:
        traces_sample_rate: '%env(SENTRY_TRACE_SAMPLE_RATE)%'
```

##### Expected Result

Traces sample rate is set to 0.

##### Actual Result

```
❯ ./bin/console

In BaseNode.php line 545:
                                                                                                                                                    
  Invalid type for path "sentry.options.traces_sample_rate". Expected "float", but got "int".                                                       
  Hint: The sampling factor to apply to transactions. A value of 0 will deny sending any transaction, and a value of 1 will send all transactions.  
```

#### sentry.yaml #2
```
parameters:
    env(SENTRY_TRACE_SAMPLE_RATE): 0.1

sentry:
    options:
        traces_sample_rate: '%env(SENTRY_TRACE_SAMPLE_RATE)%'
```

##### Expected Result

Traces sample rate is set to 0.1.

##### Actual Result

```
❯ ./bin/console

In OptionsResolver.php line 938:
                                                                                                                         
  The option "traces_sample_rate" with value "0.1" is expected to be of type "int" or "float", but is of type "string".
```
