### ISSUE TITLE
HttpClientFactory not using Symfony http_client options

### ISSUE THREAD

**Issue by poolerMF** [getsentry/sentry-symfony#574]
```
framework:
    http_client:
        default_options:
            http_version: "1.0"
            max_redirects: 2
            ...

```

**Sentry\HttpClient\HttpClientFactory** should use those defined http_client options when creating $**httpClient**
if not, then using custom HttpClient NEEDS to customizable/easy to define/change
