### ISSUE TITLE
doctrine odm support

### ISSUE THREAD

**Issue by douglasjam** [getsentry/sentry-symfony#581]
After checking the code I see there is Dbal support, but I haven't seen anything about mongo or Doctrine ODM nor in the internet, has anyone made this integration work so we can see useful mongo insights?

```
sentry:
    tracing:
        dbal:
            enabled: true
```
