### ISSUE TITLE
non-existent parameter "kernel.build_dir"

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#582]
### Environment

How do you use Sentry? SaaS

Which SDK and version?
sentry/sentry                3.3.2
sentry/sentry-symfony  4.2.2     

### Steps to Reproduce

1. Running `bin/console de:conf sentry`

### Expected Result

No errors

### Actual Result

>You have requested a non-existent parameter "kernel.build_dir". Did you mean one of these: "kernel.root_dir", "kernel.cache_dir", "kernel.logs_dir"?

**Comment by Jean85** [comment]
`kernel.build_dir` [has been added in 5.2](https://github.com/symfony/symfony/commit/e98fdc7073a3f0c4db08efe5571d7dce5f74d15d), we need to make that optional, depending on the SF version.

**Comment by Jean85** [comment]
@ste93cry sent me this:

https://github.com/getsentry/sentry-symfony/blob/master/src/DependencyInjection/SentryExtension.php#L88

We already have a safeguard for this situation, but it's probably not working in your case.

**Comment by ste93cry** [comment]
I was wondering if you solved the problem or if you can reproduce it on a fresh project to help us debug the issue. Otherwise, I will close this issue...

**Comment by bramcordie** [comment]
I ran into the same issue with Symfony 4.4.40. As a workaround I made the `in_app_exclude` Sentry option explicit and left out `%kernel.build_dir%`.

```yaml
#app/config/config.yml

sentry:
    options:
        in_app_exclude:
            - "%kernel.cache_dir%"
            - "%kernel.project_dir%/vendor"
```
