### ISSUE TITLE
Sentry and Symfony error handlers conflicts

### ISSUE THREAD

**Issue by alexander-schranz** [getsentry/sentry-symfony#609]
### Environment

How do you use Sentry?
self-hosted/on-premise

```
sentry/sdk                                 3.1.1 
sentry/sentry                              3.4.0      
sentry/sentry-symfony                      4.2.7 
```

### Steps to Reproduce

Have a symfony project with deprecations:

Run console command which triggers deprecation e.g.:

```bash
bin/console cache:clear
```

Output is normally:

<img width="848" alt="Bildschirmfoto 2022-03-31 um 12 33 41" src="https://user-images.githubusercontent.com/1698337/161035830-e7946749-7a37-4237-bc7c-e4d66c7316ad.png">

Install sentry / sentry bundle run again:

```bash
bin/console cache:clear
```

<img width="850" alt="Bildschirmfoto 2022-03-31 um 12 33 22" src="https://user-images.githubusercontent.com/1698337/161035893-6e64e4ce-3b9f-456c-aea8-7671f3ce4f89.png">

It looks for me there is some conflicts between symfony error handler (think it handles also deprecations) and the sentry error handler. 

In our case we already had disabled the `error_listener` but it does not have any effects depending on [sentry symfony monolog integration](https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration):

<details>
<summary>config/packages/sentry.yaml</summary> 

```yaml
sentry:
    dsn: "%env(SENTRY_DSN)%"
    register_error_listener: false # Disable ErrorListener to avoid duplicated events because of monolog handler
    options:
        attach_stacktrace: true # Attach stacktrace to monolog events that do not include an exception
        send_default_pii: true # Include personally identifiable information like user, cookies and headers
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

# monolog configuration for sentry
# see also: https://docs.sentry.io/platforms/php/guides/symfony/
monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface

services:
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
```

</details>

This issue is maybe related to: https://github.com/getsentry/sentry-symfony/issues/337 and maybe a `register_error_handler: false` suggested by @Jean85 could fix this issue. But I'm not sure 100% sure it seems to appear only since symfony 5.4/6.0 release and the other issue seems to be older.

### Expected Result

Do not output the deprecation notices.

### Actual Result

Outputs the deprecation notices.
