### ISSUE TITLE
Add option to exclude exceptions from reporting

### ISSUE THREAD

**Issue by ysdis** [getsentry/sentry-symfony#612]
According to current version of the Sentry PHP documentation in the [Filtering](https://docs.sentry.io/platforms/php/guides/symfony/configuration/filtering/) chapter is suggested to use `before_send` callback and catch unwanted exceptions by yourselves. There is a much easier way get around that.

Why we just can't add an option called `excluded_exceptions` that will filled with list of FQCNs (by the way this option is already implemented in the [sentry-ruby](https://github.com/getsentry/sentry-ruby) repository):

Example:
```
sentry:
    options:
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
```
