### ISSUE TITLE
Unusable trace data called in a callback

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#619]
### Environment

How do you use Sentry?
Self-hosted (Sentry 21.11.0)

Which SDK and version?
PHP 4.2.8

Used config for sentry in symfony
```
tracing:
        enabled: true
        dbal: # DB queries
            enabled: true
        cache:
            enabled: true
        twig: # templating engine
            enabled: true
```

### Steps to Reproduce

1. Create any kind of a controller for symfony for any kind of a route (POST, GET)
2. Provide a CacheInterface to it (I used redis as an adapter)
3. use code similar to
```php

return $this->cache->get(
            function (ItemInterface $item) {
                $item->expiresAfter($this->cacheTime);

                return $this->handler->handle($someDataWhatever);
            }
        );
```

### Expected Result

Trace in sentry with normal function names. At least $this->handler->handle took 50ms or similar

### Actual Result

![image](https://user-images.githubusercontent.com/5228422/165513927-4c65d3ae-121d-4595-a2f1-6a04d0c7bd78.png)
