### ISSUE TITLE
Fatal error: Declaration of Sentry\Monolog\Handler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void

### ISSUE THREAD

**Issue by teol** [getsentry/sentry-symfony#640]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP 8.1
Symfony 6.1
sentry/sentry 3.5.0
sentry/sdk 3.2.0
sentry/sentry-symfony 4.3.0

### Steps to Reproduce

On a Symfony 6.1 app:
1. composer require sentry/sentry-symfony
2. Add DSN config etc
3. Add to monolog config:
```
monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
```

### Expected Result

Nothing special, the Symfony app should work.

### Actual Result

Fatal error: Declaration of Sentry\Monolog\Handler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void in /srv/app/vendor/sentry/sentry/src/Monolog/Handler.php on line 51

### Other
I had no issue with my project using Symfony 6.0. I suspect that this issue is caused by Symfony upgrade to version 6.1. Or maybe I'm wrong and I'm just missing something.
