### ISSUE TITLE
Errors are displayed in Sentry but not anymore logged in server's logs

### ISSUE THREAD

**Issue by AppyGG** [getsentry/sentry-symfony#652]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
_symfony 5.4
sentry/sentry-symfony 4.3.0
sentry/sentry 3.7.0
sentry/sdk 3.2.0_

### Steps to Reproduce

Hello, 
when an error is thrown by my app, for example a semicolon is missing at the end of a line, the app throws an error 500. This error is catched by Sentry and appears in my sentry.io dashboard, great. But the error page displayed in the user's browser is a basic error 500 page (screenshot below) and there is no logs in my _prod.log_ file.
When i manually throw an error (by using the snippet in the [documentation for testing ](https://docs.sentry.io/platforms/php/guides/symfony/#test-the-implementation) ) it's working great. It seems like that manually thrown errors are ok, but other errors are not correctly managed.

Configs :
```
# config/packages/sentry.yml
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
```

I have an older version of my app with running with the same config except older dependencies versions :
_sentry/sentry-symfony 4.2.5
sentry/sentry 3.3.5
sentry/sdk 3.1.1_

With theses version, if an error occurs, the custom error page is used, i have a log in my _prod.log_ and Sentry receive error details.

### Expected Result

Something is logged in the _prod.log_ and most important, custom twig errors templates are used to format response to user's browser.

### Actual Result

Base Symfony error message :
![image](https://user-images.githubusercontent.com/29061649/185632435-ff99fc8f-17f5-43e5-94fb-50cbefc572e1.png)

**Comment by Jean85** [comment]
This is another issue that would be solved by #337. 

It's possible that your app config is somewhat messing with Symfony's error handler, so I don't think we can do anything here... Can you delve a bit deeper in the stacktrace?

**Comment by AppyGG** [comment]
> This is another issue that would be solved by #337.
> 
> It's possible that your app config is somewhat messing with Symfony's error handler, so I don't think we can do anything here... Can you delve a bit deeper in the stacktrace?

Ok thank you, i will take a closer look at the difference between both stack trace and give you an update :+1:

**Comment by AppyGG** [comment]
Hello, i played a little with [available configuration options](https://docs.sentry.io/platforms/php/guides/symfony/) and found one that let events go through other handlers as well as Sentry.

Working configuration in `config/packages/sentry.yaml`
```yaml
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false

        options:
            default_integrations: false
            integrations: [ ]

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::CRITICAL
                hub_id: Sentry\State\HubInterface
```

Now error pages are correctly rendered and event are logged in log files as well as sent to Sentry.
But Sentry now create 2 issues and has less context / data to work with.
- One is created with `logger=monolog.request`
- The second is created with `logger=monolog.php`
