### ISSUE TITLE
Scope accumulates irrelevant extras in long-running php processes

### ISSUE THREAD

**Issue by murat11** [getsentry/sentry-symfony#676]
### Environment

 - sentry-symfony v4.3.0
 - [roadrunner](https://github.com/php-runtime/roadrunner-symfony-nyholm) 
 - symfony 6
 - monolog 

```yaml
monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler

services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
```

### Steps to Reproduce

We are running http api using symfony in [roadrunner runtime](https://github.com/php-runtime/roadrunner-symfony-nyholm) and capturing errors with Sentry using the config like shown above. It worked well enough. With one issue: if during the processing of "current" http-request we add something into the Scope - it stays visible for future request, in particular: extras added during the handling of "previous" http-requests are visible in the data of event captured in "current" request. We did something like this in our code

```php
\Sentry\configureScope(function (Scope $scope) use ($extras, $requestTime): void {
        $key = 'http.'.(new \DateTime())->format('H:i:s(v)').'.request';
        $scope->setExtra($key, [
            'data' => $extras,
            'time' => $requestTime,
        ]);
})
```
and noticed that extras are accumulated between handling of many requests which leads to inconsistent sentry data and memory leaks in case if `$key` is unique for each event. 

I saw that for [SubRequestListener](https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/SubRequestListener.php#L39-L61) everything is accumulated inside "dedicated" scope which is erased using `Hub::popScope` on "kernel.finish_request". But this listeners are applied only to non-master requests and in our case they do not do their job because roadrunner handles all requests using `MAIN_REQUEST` request type (not SUB_REQUEST). You can see it [here](https://github.com/php-runtime/roadrunner-symfony-nyholm/blob/main/src/Runner.php#L41): 
```php
                $sfRequest = $this->httpFoundationFactory->createRequest($request);
                $sfResponse = $this->kernel->handle($sfRequest);
``` 

So I'm a bit unsure how to proceed with this issue. I can register my own listeners which will do "pushScope/popScope" for master requests too, but I'm also curious why it's not done in your library or may be I must do anything else to make it work as expected in case with roadrunner
