### ISSUE TITLE
Add an easy cron integration

### ISSUE THREAD

**Issue by vasilvestre** [getsentry/sentry-symfony#757]
### Problem Statement

Everywhere you use the CRON feature, you have to specify which environment and release you use. The initialized sentry SDK is not reused

### Solution Brainstorm

Add the capacity to reuse configured SDK maybe with an helper ?

**Comment by cleptric** [comment]
We made the process of reporting check-ins simpler in https://github.com/getsentry/sentry-php/releases/tag/3.21.0

See #719 for more context on this.

**Comment by cleptric** [comment]
How does your `config/packages/sentry.yaml` file look like?

**Comment by vasilvestre** [comment]
> How does your `config/packages/sentry.yaml` file look like?

```yaml
parameters:
    env(SENTRY_ENV): undefined
    env(SENTRY_DSN):
    env(VERSION): undefined
    env(SENTRY_TRACE_SAMPLE_RATE): '0.1'

sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(SENTRY_ENV)%'
        traces_sample_rate: '%env(float:SENTRY_TRACE_SAMPLE_RATE)%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
```

The SENTRY_ENV is set to "prod", "staging", "preprod" or "dev" depending of the environment. When I ran my test with SENTRY_ENV set to "dev", production was the environment reported in Sentry cron.
