### ISSUE TITLE
How to disable sentry on dev environment ?

### ISSUE THREAD

**Issue by ctaverne** [getsentry/sentry-symfony#76]
Hi,

Please could you give me how to properly disable sentry on dev environment ?
What is the best practice ?

thanks

**Comment by cmmata** [comment]
I don't know if there's another way to do it, but I set an empty parameter in dev environment
```
#config.yml
sentry:
    dsn: "%sentry_dsn%"
    release: "%version%"

#parameters_dev.yml
sentry_dsn: ''
```
Also, in Sentry project I go to incoming filters in configuration and I put 127.0.0.1 in `Filter errors from these IP addresses`.
