### ISSUE TITLE
Sentry timeouts don't work on our server

### ISSUE THREAD

**Issue by xevolic** [getsentry/sentry-symfony#777]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.5.0

### Steps to reproduce

We have an application, which we develop in Docker environment.

We added three options to Sentry configuration in `sentry.yaml` file:
```yaml
    options:
        attach_stacktrace: true
        send_attempts: '%env(int:SENTRY_RESEND_ATTEMPTS)%'
        http_connect_timeout: '%env(int:SENTRY_HTTP_CONNECT_TIMEOUT)%'
        http_timeout: '%env(int:SENTRY_HTTP_TIMEOUT)%'
        environment: '%kernel.environment%'
        error_types: 'E_ALL & ~E_NOTICE & ~E_DEPRECATED'
        release: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
```

Our values are:
```
SENTRY_RESEND_ATTEMPTS=0
SENTRY_HTTP_CONNECT_TIMEOUT=1
SENTRY_HTTP_TIMEOUT=2
```

We tested these timeouts in Docker environment and all response times from our backend application were correct.

But when we deployed this application to our server they seems to be ignored.

We tested Sentry timeout with some page with `sleep(10);` to get response after 10 sec.

This approach worked in Docker, but does not work on the server: we need to wait these 10 seconds for Sentry, but it should be quit after 2 seconds (timeout limit reached).

Can you help us in finding what we are doing wrong?

### Expected result

Sentry timeout should work as expected.

### Actual result

We need to wait for e..g 10 seconds for page, which simulates Sentry.

**Comment by cleptric** [comment]
The defaults are applied by the underlying PHP SDK here https://github.com/getsentry/sentry-php/blob/3.x/src/Options.php#L25-L35.
Hence I'm wondering why you see a 10 second timeout, it almost feels like that the env vars you set on production somehow set these options to `null`.

**Comment by xevolic** [comment]
@cleptric thanks for your reply

I forgot  to mention that our application uses Symfony framework and uses following configuration file (`sentry.yaml`):
```yaml
sentry:
    dsn: '%env(SENTRY_DSN)%'

#    If you are using Monolog, you also need these additional configuration and services to log the errors correctly:
#    https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
    register_error_listener: false

    options:
        attach_stacktrace: true
        send_attempts: '%env(int:SENTRY_RESEND_ATTEMPTS)%'
        http_connect_timeout: '%env(int:SENTRY_HTTP_CONNECT_TIMEOUT)%'
        http_timeout: '%env(int:SENTRY_HTTP_TIMEOUT)%'
        environment: '%kernel.environment%'
        error_types: 'E_ALL & ~E_NOTICE & ~E_DEPRECATED'
        release: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

```

We try to simulate 10-second delay of Sentry application to check if timeout values are working as expected.

Our application connects to SMTP server and if it rejects our request, an error is sent to Sentry.
In that case, with high traffic, we killed Sentry some time ago and want to prevent it from happening again.

We can increase 10-second delay to 15 or 30 seconds... we just chose 10 at the moment.
