### ISSUE TITLE
Attempted to call an undefined method named "setCallbackWrapper" of class "Symfony\Component\Cache\Adapter\TraceableAdapter"

### ISSUE THREAD

**Issue by loevgaard** [getsentry/sentry-symfony#840]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

SDK: 3.22, bundle: 4.14

### Steps to reproduce

I added this configuration:

```yaml
framework:
    cache:
        pools:
            async.cache:
                early_expiration_message_bus: messenger.default_bus
```

from this page: https://symfony.com/doc/current/cache.html#computing-cache-values-asynchronously

and got this exception:

```
[Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
Attempted to call an undefined method named "setCallbackWrapper" of class "Symfony\Component\Cache\Adapter\TraceableAdapter".
```

The method `setCallbackWrapper` it's trying to call is defined in the `\Symfony\Component\Cache\Traits\ContractsTrait` and it might be therefore it's assumed that it's also present on the `TraceableAdapter`. Because Sentry decorates the `TraceableAdapter` with the `Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapter` this will cause an exception.

A possible solution could be to just add the method `setCallbackWrapper` to your `\Sentry\SentryBundle\Tracing\Cache\TraceableCacheAdapterTrait`
