### ISSUE TITLE
TRACES_SAMPLE_RATE on 0.0 and still sending transactions to Sentry

### ISSUE THREAD

**Issue by jeffreymoelands** [getsentry/sentry-symfony#877]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

5.0.0

### Steps to reproduce

Config

```
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            environment: '%env(SENTRY_ENVIRONMENT)%'
            # Specify a fixed sample rate (https://docs.sentry.io/platforms/php/guides/symfony/performance/)
            traces_sample_rate: '%env(float:SENTRY_TRACES_SAMPLE_RATE)%'
            ignore_exceptions:
                - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                - Symfony\Component\Security\Core\Exception\AccessDeniedException

        # If you are using Monolog, you also need this additional configuration to log the errors correctly:
        # https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
        register_error_listener: false
        register_error_handler: false

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
                channels: ['!event', '!doctrine', '!deprecation']
```

.env:
```
SENTRY_TRACES_SAMPLE_RATE=0.0
```

### Expected result

Zero transactions in the overview

### Actual result

![Image](https://github.com/user-attachments/assets/8741f20c-dbe2-4db7-a14c-364173593cbc)
