### ISSUE TITLE
Add more configuration for tracing

### ISSUE THREAD

**Issue by OrigamiKill** [getsentry/sentry-symfony#882]
### Problem Statement

On high-load projects, there are requests that should not trigger performance data collection, but it would still be good to keep the default "traceparent" header for next requests. Because of this, we almost always have to rewrite TracingRequestListener::handleKernelRequestEvent in order to ignore the existence of the "traceparent" header.

### Solution Brainstorm

It would be very convenient to have the option to select which headers will trigger tracing. For example:
```
...
sentry:
    ...
    options:
        performance_headers:
            - sentry-trace
            - my-random-header
```
