### ISSUE TITLE
ignore_transactions seems not to work

### ISSUE THREAD

**Issue by FranzBruckner** [getsentry/sentry-symfony#885]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.14.0

### Steps to reproduce

configured sentry to ignore specific transaction.
Using it in a symfony 4.4 environment

```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
        ignore_transactions:
            - 'POST /api/1.0/cat/conGroups/.*'
            - 'POST /api/1.0/cat/mea/.*'
        send_default_pii: true
        traces_sample_rate: 0.01
```

### Expected result

All POST-Requests to 
- /api/1.0/cat/conGroups/.*
- POST /api/1.0/cat/mea/.*

should not be sent to sentry.
Even those from a different subdomain, like https://api.tld.com/api. Web-UI is served via https://tld.com

### Actual result

Requests to the above URLs are sent to sentry, eating up the paid quota.
