### ISSUE TITLE
Support `logger` option

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-symfony#892]
There is currently no convenient way to setup the logger for debugging purposes.
We should widen the accepted options values in the PHP SDK to support usage like:

```yaml
sentry:
    dsn: "%env(SENTRY_DSN)%"
    options:
        logger: "sentry.logger"

services:
  sentry.logger:
    class: 'Sentry\Logger\DebugFileLogger'
    arguments:
        $filePath: '../../var/log/sentry.log'
```
