### ISSUE TITLE
Error in documentation by "sentry.options.enable_tracing" field and what difference between "sentry.options.enable_tracing" and "sentry.tracing.enabled"

### ISSUE THREAD

**Issue by motoronik** [getsentry/sentry-symfony#907]
### How do you use Sentry?

I use - `self-hosted`

### SDK version

4.10.0

### Steps to reproduce

Hi, I'm using a self-hosted solution and 
- `sentry/sentry 4.10.0 PHP SDK for Sentry (http://sentry.io)`
- `sentry/sentry-symfony 5.1.0 Symfony integration for Sentry (http://getsentry.com)`

My question is related to the work of tracking and an attempt to disable it, specifically with these fields:
- `sentry.options.enable_tracing`
- `sentry.options.traces_sample_rate`
- `sentry.tracing.enabled`

I wanted to have a ready-made setup where I could specify all the necessary fields (`sentry.options.traces_sample_rate`, `sentry.tracing.dbal.enabled` and others) and use a any boolean field to enable and disable tracing in all application.

I thought it was enough to switch `sentry.tracing.enabled` to `false` and tracing would be disabled, but I was wrong and tracing continued collect and send tracing data. In this config sentry did not disable tracing and continued to collect tracing data.

```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
        profiles_sample_rate: 0.1
        traces_sample_rate: 0.1
    tracing:
        enabled: false
        dbal:
            enabled: true
            connections:
                - default
        cache:
            enabled: true
        twig:
            enabled: false
```

Next, I read the documentation and found that there is a field [enable-tracing](https://docs.sentry.io/platforms/php/guides/symfony/configuration/options/#enable-tracing ) the documentation says that it is this field that is responsible for enabling and disabling tracing, but it is also written that: 

> Note that traces-sample-rate and traces-sampler take precedence over this option

That is, according to the documentation, the configuration described below will send tracking despite the Boolean value of the enable_tracing field being false. 

```
sentry:
    options:
        ...
        enable_tracing: false
        traces_sample_rate: 1
```

I decided to check and described this configuration, but I did not see any new tracking entries in the UI, although the documentation says that the `profiles_sample_rate` field is a higher priority than `enable_tracing`, and after I changed the `enable_tracing` field to true, the tracking began to be collected and displayed in the UI

Does the documentation not correspond to reality? In this regard, I have some questions, please tell me the answer to them:
- What is the difference between the `sentry.options.enable_tracing` and `sentry.tracing.enabled` fields, in which cases should I use which field?
- Which field has a higher priority of `sentry.options.enable_tracing` or `sentry.options.profiles_sample_rate`, the documentation describing the `sentry.options.enable_tracing` field is not true?
- In documentation i dont found info about field `sentry.options.profiles_sample_rate` by this links [options](https://docs.sentry.io/platforms/php/guides/symfony/configuration/options/) and [symfony-options](https://docs.sentry.io/platforms/php/guides/symfony/configuration/symfony-options/) but in this link [profiling](https://docs.sentry.io/platforms/php/guides/symfony/profiling/) i found  a mention without a detailed description, can you describe this field too?

I'll be waiting for an answer, thanks for your help!

### Expected result

In this configuration tracing must be collect and send, about this write in documentation [enable-tracing](https://docs.sentry.io/platforms/php/guides/symfony/configuration/options/#enable-tracing)

```
sentry:
    options:
        ...
        enable_tracing: false
        traces_sample_rate: 1
```

### Actual result

In this configuration tracing not collect and send
```
sentry:
    options:
        ...
        enable_tracing: false
        traces_sample_rate: 1
```

**Comment by cleptric** [comment]
`enable_tracing` is deprecated, and as in the docs, use either or, not both.

`profiles_sample_rate` has nothing to do with tracing and instead sets the sample rate for profiling. https://docs.sentry.io/platforms/php/guides/symfony/profiling/

The options `sentry.tracing.enabled` controls which integrations create telemetry, https://docs.sentry.io/platforms/php/guides/symfony/tracing/instrumentation/automatic-instrumentation/.

**Comment by motoronik** [comment]
Sorry for asking again, but after your answer I became even more confused about how these fields work.

My updated configuration looks like this, now tracing is not collected
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
        enable_tracing: false
        traces_sample_rate: 0
        profiles_sample_rate: 0
    tracing:
        enabled: false
```

The documentation states that the `traces_sample_rate` field is more important than `enable_tracing` and if I specify 1 for `traces_sample_rate` in the current configuration, then tracing should be collected, I tested it locally with the following configuration

```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
        enable_tracing: false
        traces_sample_rate: 1
        profiles_sample_rate: 1
    tracing:
        enabled: false
```

But this is not true, in this configuration tracing is not collected, and it starts to be collected only after I switch the `enable_tracing` flag to true.

**Question №1**
It turns out that the `enable_tracing` flag is still used? And is it more important than `traces_sample_rate`?

**Question №2**
What is the difference between `sentry.options.enable_tracing` and `sentry.tracing.enabled`, what is the `sentry.tracing.enabled` flag responsible for?

Thanks for your answers!
