### ISSUE TITLE
Exceptions are reported despite being on the exclude list

### ISSUE THREAD

**Issue by MarcinOrlowski** [getsentry/sentry-symfony#919]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

"sentry/sentry-symfony": "^5.2"

### Steps to reproduce

I am excluded some exceptions in `config/packages/sentry.yaml`, restarted the server and I still see these exceptions reported:

```
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            attach_stacktrace: true
            # Add request headers, cookies, IP address and the authenticated user
            # see https://docs.sentry.io/platforms/php/data-management/data-collected/ for more info
            # send_default_pii: true
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'     # low priority, we may re-evaluate this later
                - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'  # usually attempts to log in to admin panel
```

The class names are copied from the reports so I believe this is how Sentry sees them. But despite that it is still being logged and reported.

### Expected result

Excluded exceptions should be ignored.

### Actual result

Both `NotFoundHttpException` and `AccessDeniedException` show up in reports.
